-- AlterTable
ALTER TABLE `Donaciones` MODIFY `createdAt` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `updatedAt` TIMESTAMP(6) NULL;

-- AlterTable
ALTER TABLE `Donantes` MODIFY `createdAt` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `updatedAt` TIMESTAMP(6) NULL;

-- AlterTable
ALTER TABLE `Historial_acciones` MODIFY `createdAt` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6);

-- AlterTable
ALTER TABLE `Personas` MODIFY `createdAt` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `updatedAt` TIMESTAMP(6) NULL;

-- AlterTable
ALTER TABLE `Receptores` MODIFY `createdAt` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `updatedAt` TIMESTAMP(6) NULL;

-- AlterTable
ALTER TABLE `Solicitudes` MODIFY `createdAt` TIMESTAMP(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY `updatedAt` TIMESTAMP(6) NULL;
